server:
  port: 8088

spring:
  application:
    # 应用名称
    name: colorful-service-gateway
  jackson:
    default-property-inclusion: non_null

  cloud:
    nacos:
      discovery:
        server-addr: 10.12.12.188:8848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: COLORFUL-SERVICE-PROVIDER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://colorful-service-provider
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
        - id: COLORFUL-SERVICE-CONSUMER
          uri: lb://colorful-service-consumer
          predicates:
            - Method=GET,POST

management:
  endpoints:
    web:
      exposure:
        include: "*"